# -*- coding: utf-8 -*-
"""prevecion overfitting EXOGENAS-TOTAL_DATACOES_OP_SKFORECAST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2GGJR_-1hEd9mhFYJkVfRtnPqFNBjPj

# PRUEBA DE LIBRERIAS ML SKY

**Cargar librerias**
"""

import os, sys
from google.colab import drive
drive.mount('/content/drive')
nb_path = '/content/notebooks'
# os.symlink('/content/drive/My Drive/Colab Notebooks', nb_path) # Removed this line
sys.path.insert(0,nb_path)

import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks')

"""**Instalar libreras faltantes**"""

#pip install skforecast

"""**LLAMADO A LIBRERIAS INSTALADAS**"""

# DATOS CSV
# ==============================================================================
import numpy as np
import pandas as pd
from astral.sun import sun
from astral import LocationInfo
from skforecast.datasets import fetch_dataset
from feature_engine.datetime import DatetimeFeatures
from feature_engine.creation import CyclicalFeatures
from feature_engine.timeseries.forecasting import WindowFeatures

# Plots
# ==============================================================================
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.graphics.tsaplots import plot_pacf
from skforecast.plot import plot_residuals
import plotly.graph_objects as go
import plotly.io as pio
import plotly.offline as poff
pio.templates.default = "seaborn"
poff.init_notebook_mode(connected=True)
plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams.update({'font.size': 8})

# PREDICCION
# ==============================================================================
import skforecast
import lightgbm
import sklearn
from lightgbm import LGBMRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.feature_selection import RFECV
from skforecast.recursive import ForecasterEquivalentDate, ForecasterRecursive
from skforecast.direct import ForecasterDirect
from skforecast.model_selection import TimeSeriesFold, bayesian_search_forecaster, backtesting_forecaster
from skforecast.feature_selection import select_features
from skforecast.preprocessing import RollingFeatures
from skforecast.plot import calculate_lag_autocorrelation, plot_residuals
from skforecast.metrics import calculate_coverage
import shap
from xgboost import XGBRegressor
from skforecast.model_selection import TimeSeriesFold, grid_search_forecaster, backtesting_forecaster


import warnings
warnings.filterwarnings('once')

color = '\033[1m\033[38;5;208m'
print(f"{color}Version skforecast: {skforecast.__version__}")
print(f"{color}Version scikit-learn: {sklearn.__version__}")
print(f"{color}Version lightgbm: {lightgbm.__version__}")
print(f"{color}Version pandas: {pd.__version__}")
print(f"{color}Version numpy: {np.__version__}")

"""**INGRESO DE DATOS**"""

# IMPORTAR DESDE DRIVE
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/SCRIPTS/ARTICULO/PARA LA OPERACION/CON TODAS LAS VARIABLES EXOGENAS/DATA_COES-TEMP-HOLL-PIB-ACC-POBL.csv')
data.info()
data

"""# PREPARACION DE DATOS

# Verificar que un índice temporal esté completo
"""

data['Time'] = pd.to_datetime(data['Time'])
data = data.set_index('Time')
data = data.asfreq('30min')
data = data.sort_index()
data.head(2)

data.info()
data

#data['PIB'].plot(figsize=(12, 6))
#plt.title('PIB M$')
#plt.xlabel('Time')
#plt.ylabel('PIB (M$)')
#plt.grid(True)
#plt.show()

#data['Temperature'].plot(figsize=(12, 6))
#plt.title('Temperatura °C')
#plt.xlabel('Time')
#plt.ylabel('Temperatura (°C)')
#plt.grid(True)
#plt.show()

data.index



"""VERIFICACION DE QUE TODAS LAS FILAS Y COLUMNAS TENGAN DATOS"""

start_date = data.index.min()
end_date = data.index.max()
complete_date_range = pd.date_range(start=start_date, end=end_date, freq=data.index.freq)
is_index_complete = (data.index == complete_date_range).all()
print(f"Index complete: {is_index_complete}")
print(f"Number of rows with missing values: {data.isnull().any(axis=1).mean()}")
freq = data.index.freq
freq

#data['Demand'].plot(figsize=(12, 6))
#plt.title('DEMANDA MW')
#plt.xlabel('Time')
#plt.ylabel('Demanda (MW)')
#plt.grid(True)
#plt.show()

"""DEPURADO DATOS POR HORA"""

data = (
    data
    .resample(rule="30T", closed="left", label="right")
    .agg({
        "Demand": "mean",
        "PROG. DIARIA": "mean",
        "PROG. SEMANAL": "mean",
        #"Time": "mean",
    })
)
data
#data.to_csv("basededatoscoesdep.csv", index=False)

"""# GRAFICA DE LA SERIE DE TIEMPO"""

data = data.loc['2006-01-08 01:00:00':'2025-08-31 23:00:00'].copy()
end_train = '2021-12-31 23:59:00'
end_validation = '2025-07-01 23:59:00'

data_train = data.loc[: end_train, :].copy()
data_val   = data.loc[end_train:end_validation, :].copy()
data_test  = data.loc[end_validation:, :].copy()

print(f"Datos de entrenamiento      : {data_train.index.min()} --- {data_train.index.max()}  (n={len(data_train)})")
print(f"Datos de validacion : {data_val.index.min()} --- {data_val.index.max()}  (n={len(data_val)})")
print(f"Datos de prueba       : {data_test.index.min()} --- {data_test.index.max()}  (n={len(data_test)})")

# SERIE DE TIEMPO CON PERIODOS DE ENTRENAMIENTO Y PRUEBA
# ==============================================================================
fig = go.Figure()
fig.add_trace(go.Scatter(x=data_train.index, y=data_train['Demand'], mode='lines', name='ENTRENAMIENTO R'))
fig.add_trace(go.Scatter(x=data_val.index, y=data_val['Demand'], mode='lines', name='ENTRENAMIENTO D'))
fig.add_trace(go.Scatter(x=data_test.index, y=data_test['Demand'], mode='lines', name='ENTRENAMIENTO S'))
fig.update_layout(
    title='Demanda Electrica por Hora',
    xaxis_title="Tiempo",
    yaxis_title="Demanda",
    legend_title="Partition:",
    width=800,
    height=400,
    margin=dict(l=20, r=20, t=35, b=20),
    legend=dict(orientation="h", yanchor="top", y=1, xanchor="left", x=0.001)
)
#fig.update_xaxes(rangeslider_visible=True)
#fig.show()
### visualizacion de de la serie de tiempo
fig.update_xaxes(rangeslider_visible=True)
fig.write_html('hourly_energy_demand.html')
from IPython.display import HTML
HTML(filename='hourly_energy_demand.html')

import plotly.graph_objects as go
from IPython.display import HTML

# --- Figura MDPI con título y fondo limpio ---
fig = go.Figure()

# Trazas
fig.add_trace(go.Scatter(
    x=data_train.index, y=data_train['Demand'],
    mode='lines', name='Entrenamiento', line=dict(width=2)
))
fig.add_trace(go.Scatter(
    x=data_val.index, y=data_val['Demand'],
    mode='lines', name='Validación', line=dict(width=2)
))
fig.add_trace(go.Scatter(
    x=data_test.index, y=data_test['Demand'],
    mode='lines', name='Prueba', line=dict(width=2)
))

# Layout limpio
fig.update_layout(
    title={
        'text': "<b>Demanda Eléctrica</b>",
        'y':0.95,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': {'family': 'Arial, sans-serif', 'size':16, 'color':'black'}
    },
    width=700,
    height=450,
    margin=dict(l=60, r=40, t=70, b=60),
    paper_bgcolor='white',
    plot_bgcolor='white',
    xaxis=dict(
        title="<b>Años</b>",
        title_font=dict(family='Arial, sans-serif', size=12),
        showgrid=False,   # QUITAR cuadrículas
        showline=True,
        linewidth=1,
        linecolor='black',
        tickformat='%Y',
        ticks="inside",
        tickfont=dict(family='Arial, sans-serif', size=11)
    ),
    yaxis=dict(
        title="<b>Demanda [MW]</b>",
        title_font=dict(family='Arial, sans-serif', size=12),
        showgrid=False,   # QUITAR cuadrículas
        showline=True,
        linewidth=1,
        linecolor='black',
        ticks="inside",
        tickfont=dict(family='Arial, sans-serif', size=11)
    ),
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.3,
        xanchor="center",
        x=0.5,
        font=dict(family='Arial, sans-serif', size=11),
        borderwidth=0
    )
)

# Mostrar figura
fig.show()

# Guardar HTML interactivo
fig.write_html('prediction_vs_real_test_mdpi.html')
HTML(filename='prediction_vs_real_test_mdpi.html')

import plotly.graph_objects as go
from IPython.display import HTML

fig = go.Figure()

# Trazas
fig.add_trace(go.Scatter(
    x=data_train.index, y=data_train['Demand'],
    mode='lines', name='Entrenamiento', line=dict(width=2)
))
fig.add_trace(go.Scatter(
    x=data_val.index, y=data_val['Demand'],
    mode='lines', name='Validación', line=dict(width=2)
))
fig.add_trace(go.Scatter(
    x=data_test.index, y=data_test['Demand'],
    mode='lines', name='Prueba', line=dict(width=2)
))

# Layout con Roboto
fig.update_layout(
    font=dict(  # 👈 FUENTE GLOBAL
        family='Roboto, Arial, sans-serif',
        size=12,
        color='black'
    ),
    title={
        'text': "<b>Datos de entrenamiento, validacion y prueba</b>",
        'y':0.95,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': {'family': 'Roboto, Arial, sans-serif', 'size':18}
    },
    width=700,
    height=450,
    margin=dict(l=60, r=40, t=70, b=60),
    paper_bgcolor='white',
    plot_bgcolor='white',
    xaxis=dict(
        title="<b>Años</b>",
        showgrid=False,
        showline=True,
        linewidth=1,
        linecolor='black',
        tickformat='%Y',
        ticks="inside",
        tickfont=dict(family='Roboto, Arial, sans-serif', size=12)
    ),
    yaxis=dict(
        title="<b>Demanda [MW]</b>",
        showgrid=False,
        showline=True,
        linewidth=1,
        linecolor='black',
        ticks="inside",
        tickfont=dict(family='Roboto, Arial, sans-serif', size=12)
    ),
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.3,
        xanchor="center",
        x=0.5,
        font=dict(family='Roboto, Arial, sans-serif', size=11),
        borderwidth=0
    )
)

fig.show()

# Guardar HTML
fig.write_html('prediction_vs_real_test_mdpi.html')
HTML(filename='prediction_vs_real_test_mdpi.html')

import plotly.graph_objects as go
from IPython.display import HTML
import pandas as pd

# --- Crear serie continua combinando train, val y test ---
# Suponiendo que los índices no se solapan
data_full = pd.concat([data_train['Demand'], data_val['Demand'], data_test['Demand']])

fig = go.Figure()

# Trazar la serie completa como una sola línea
fig.add_trace(go.Scatter(
    x=data_full.index,
    y=data_full.values,
    mode='lines',
    name='Demanda Total',  # solo una traza
    line=dict(width=2, color='blue')
))

# --- Layout con Roboto y estilo MDPI ---
fig.update_layout(
    font=dict(
        family='Roboto, Arial, sans-serif',
        size=12,
        color='black'
    ),
    title={
        'text': "<b>Demanda Eléctrica Perú</b>",
        'y':0.95,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': {'family': 'Roboto, Arial, sans-serif', 'size':18}
    },
    width=700,
    height=450,
    margin=dict(l=60, r=40, t=70, b=60),
    paper_bgcolor='white',
    plot_bgcolor='white',
    xaxis=dict(
        title="<b>Años</b>",
        showgrid=False,
        showline=True,
        linewidth=1,
        linecolor='black',
        tickformat='%Y',
        ticks="inside",
        tickfont=dict(family='Roboto, Arial, sans-serif', size=12)
    ),
    yaxis=dict(
        title="<b>Demanda [MW]</b>",
        showgrid=False,
        showline=True,
        linewidth=1,
        linecolor='black',
        ticks="inside",
        tickfont=dict(family='Roboto, Arial, sans-serif', size=11)
    ),
    showlegend=False  # ❌ quitar leyenda
)

# Mostrar figura
fig.show()

# Guardar HTML con Roboto
fig.write_html(
    'prediction_vs_real_total_mdpi.html',
    include_plotlyjs='cdn',
    full_html=True,
    post_script="""
    var link = document.createElement('link');
    link.href = 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap';
    link.rel = 'stylesheet';
    document.head.appendChild(link);
    """
)

HTML(filename='prediction_vs_real_total_mdpi.html')

data = (
    data
    .resample(rule="30T", closed="left", label="right")
    .agg({
        "Demand": "mean",
        #"PROG. DIARIA": "mean",
        #"PROG. SEMANAL": "mean",
        #"Time": "mean",
    })
)
data
#data.to_csv("basededatoscoesdep.csv", index=False)

data = data.loc['2006-01-08 01:00:00':'2025-08-31 23:00:00'].copy()
end_train = '2024-07-01 23:59:00'
end_validation = '2025-07-01 23:59:00'

data_train = data.loc[: end_train, :].copy()
data_val   = data.loc[end_train:end_validation, :].copy()
data_test  = data.loc[end_validation:, :].copy()

print(f"Datos de entrenamiento      : {data_train.index.min()} --- {data_train.index.max()}  (n={len(data_train)})")
print(f"Datos de validacion : {data_val.index.min()} --- {data_val.index.max()}  (n={len(data_val)})")
print(f"Datos de prueba       : {data_test.index.min()} --- {data_test.index.max()}  (n={len(data_test)})")

# SERIE DE TIEMPO CON PERIODOS DE ENTRENAMIENTO Y PRUEBA
# ==============================================================================
fig = go.Figure()
fig.add_trace(go.Scatter(x=data_train.index, y=data_train['Demand'], mode='lines', name='train'))
fig.add_trace(go.Scatter(x=data_test.index, y=data_test['Demand'], mode='lines', name='val'))
fig.add_trace(go.Scatter(x=data_val.index, y=data_val['Demand'], mode='lines', name='test'))

# Marcar el período 2020-03-16 hasta 2020-04-21 de color rojo transparente
fig.add_vrect(x0="2020-03-16", x1="2020-04-21", fillcolor="red", opacity=0.3, layer="below", line_width=0)

# Marcar el período 2020-04-21 hasta 2020-11-01 de color negro transparente
fig.add_vrect(x0="2020-04-21", x1="2020-11-01", fillcolor="black", opacity=0.3, layer="below", line_width=0)

# Añadir anotaciones de texto explícitas para mejor visibilidad
fig.add_annotation(
    x="2020-04-01",  # Fecha aproximada a la mitad del período de confinamiento
    y=1.08,          # Aumentar la posición vertical
    xref="x",        # x-coordenada se refiere al eje x del gráfico
    yref="paper",    # y-coordenada se refiere al espacio del papel (0 a 1)
    text="Confinamiento",
    showarrow=False,
    font=dict(size=10, color="red"),
    align="center"
)
fig.add_annotation(
    x="2020-07-15",  # Fecha aproximada a la mitad del período de recuperación
    y=1.08,          # Aumentar la posición vertical
    xref="x",
    yref="paper",
    text="Recuperacion",
    showarrow=False,
    font=dict(size=10, color="black"),
    align="center"
)

fig.update_layout(
    title='Demanda Electrica por Hora',
    xaxis_title="Tiempo",
    yaxis_title="Demanda",
    legend_title="Partition:",
    width=800,
    height=400,
    margin=dict(l=20, r=20, t=35, b=20),
    legend=dict(orientation="h", yanchor="top", y=1, xanchor="left", x=0.001) # Asegurarse de que la leyenda no se solape
)
#fig.update_xaxes(rangeslider_visible=True)
#fig.show()
### visualizacion de de la serie de tiempo
fig.update_xaxes(rangeslider_visible=True)
fig.write_html('hourly_energy_demand.html')
from IPython.display import HTML
HTML(filename='hourly_energy_demand.html')

import plotly.graph_objects as go
from IPython.display import HTML

fig = go.Figure()

# Trazas (corregidas)
fig.add_trace(go.Scatter(
    x=data_train.index, y=data_train['Demand'],
    mode='lines', name='Entrenamiento', line=dict(width=2)
))
fig.add_trace(go.Scatter(
    x=data_val.index, y=data_val['Demand'],
    mode='lines', name='Validación', line=dict(width=2)
))
fig.add_trace(go.Scatter(
    x=data_test.index, y=data_test['Demand'],
    mode='lines', name='Prueba', line=dict(width=2)
))

# Periodos sombreados
fig.add_vrect(
    x0="2020-03-16", x1="2020-04-21",
    fillcolor="red", opacity=0.2,
    layer="below", line_width=0
)
fig.add_vrect(
    x0="2020-04-21", x1="2020-11-01",
    fillcolor="black", opacity=0.15,
    layer="below", line_width=0
)

# Anotaciones (estilo limpio)
fig.add_annotation(
    x="2020-04-01",
    y=1.05,
    xref="x",
    yref="paper",
    text="<b>Confinamiento</b>",
    showarrow=False,
    font=dict(family='Roboto, Arial, sans-serif', size=11, color="red"),
    align="center"
)

fig.add_annotation(
    x="2020-07-15",
    y=1.05,
    xref="x",
    yref="paper",
    text="<b>Recuperación</b>",
    showarrow=False,
    font=dict(family='Roboto, Arial, sans-serif', size=11, color="black"),
    align="center"
)

# Layout estilo MDPI
fig.update_layout(
    font=dict(
        family='Roboto, Arial, sans-serif',
        size=12,
        color='black'
    ),
    title={
        'text': "<b>Demanda Eléctrica</b>",
        'y':0.95,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': {'family': 'Roboto, Arial, sans-serif', 'size':18}
    },
    width=700,
    height=450,
    margin=dict(l=60, r=40, t=70, b=60),
    paper_bgcolor='white',
    plot_bgcolor='white',
    xaxis=dict(
        title="<b>Años</b>",
        showgrid=False,
        showline=True,
        linewidth=1,
        linecolor='black',
        tickformat='%Y',
        ticks="inside",
        tickfont=dict(family='Roboto, Arial, sans-serif', size=11),
        rangeslider=dict(visible=False)
    ),
    yaxis=dict(
        title="<b>Demanda [MW]</b>",
        showgrid=False,
        showline=True,
        linewidth=1,
        linecolor='black',
        ticks="inside",
        tickfont=dict(family='Roboto, Arial, sans-serif', size=11)
    ),
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.3,
        xanchor="center",
        x=0.5,
        font=dict(family='Roboto, Arial, sans-serif', size=11),
        borderwidth=0
    )

)


fig.show()

# Exportar HTML con Roboto
fig.write_html(
    'hourly_energy_demand.html',
    include_plotlyjs='cdn',
    full_html=True,
    post_script="""
    var link = document.createElement('link');
    link.href = 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap';
    link.rel = 'stylesheet';
    document.head.appendChild(link);
    """
)

HTML(filename='hourly_energy_demand.html')

import plotly.graph_objects as go
from IPython.display import HTML

# Crear figura
fig = go.Figure()

# --- Trazas de la serie temporal ---
fig.add_trace(go.Scatter(
    x=data_train.index, y=data_train['Demand'],
    mode='lines', name='Entrenamiento', line=dict(width=2, color='blue')
))
fig.add_trace(go.Scatter(
    x=data_val.index, y=data_val['Demand'],
    mode='lines', name='Validación', line=dict(width=2, color='orange')
))
fig.add_trace(go.Scatter(
    x=data_test.index, y=data_test['Demand'],
    mode='lines', name='Prueba', line=dict(width=2, color='green')
))

# --- Periodos sombreados ---
fig.add_vrect(
    x0="2020-03-16", x1="2020-04-21",
    fillcolor="red", opacity=0.2,
    layer="below", line_width=0
)
fig.add_vrect(
    x0="2020-04-21", x1="2020-11-01",
    fillcolor="black", opacity=0.15,
    layer="below", line_width=0
)

# --- Anotaciones ---
fig.add_annotation(
    x="2020-04-01",
    y=1.05,
    xref="x",
    yref="paper",
    text="<b>Confinamiento</b>",
    showarrow=False,
    font=dict(family='Roboto, Arial, sans-serif', size=12, color="red"),
    align="center"
)
fig.add_annotation(
    x="2020-07-15",
    y=1.05,
    xref="x",
    yref="paper",
    text="<b>Recuperación</b>",
    showarrow=False,
    font=dict(family='Roboto, Arial, sans-serif', size=12, color="black"),
    align="center"
)

# --- Layout estilo MDPI ---
fig.update_layout(
    font=dict(
        family='Roboto, Arial, sans-serif',
        size=12,
        color='black'
    ),
    title={
        'text': "<b>Demanda Eléctrica Perú</b>",
        'y':0.95,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': {'family': 'Roboto, Arial, sans-serif', 'size':20}
    },
    width=700,
    height=450,
    margin=dict(l=60, r=40, t=70, b=60),
    paper_bgcolor='white',
    plot_bgcolor='white',
    xaxis=dict(
        title="<b>Años</b>",
        showgrid=False,
        showline=True,
        linewidth=1,
        linecolor='black',
        tickformat='%Y',
        ticks="inside",
        tickfont=dict(family='Roboto, Arial, sans-serif', size=11),
        rangeslider=dict(visible=False)  # ❌ Sin barra inferior
    ),
    yaxis=dict(
        title="<b>Demanda [MW]</b>",
        showgrid=False,
        showline=True,
        linewidth=1,
        linecolor='black',
        ticks="inside",
        tickfont=dict(family='Roboto, Arial, sans-serif', size=11)
    ),
    showlegend=False  # ❌ Quitar leyenda
)

# --- Mostrar figura ---
fig.show()

# --- Guardar HTML con Roboto ---
fig.write_html(
    'hourly_energy_demand.html',
    include_plotlyjs='cdn',
    full_html=True,
    post_script="""
    var link = document.createElement('link');
    link.href = 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap';
    link.rel = 'stylesheet';
    document.head.appendChild(link);
    """
)

# --- Mostrar HTML interactivo ---
HTML(filename='hourly_energy_demand.html')

"""ZOOM EN LOS DATOS"""

#zoom = ('2019-07-01 14:00:00', '2020-01-01 14:00:00')
#fig = plt.figure(figsize=(8, 4))
#grid = plt.GridSpec(nrows=8, ncols=1, hspace=0.6, wspace=0)
#main_ax = fig.add_subplot(grid[:3, :])
#data.Demand.plot(ax=main_ax, c='black', alpha=0.5, linewidth=0.5)
#min_y = min(data.Demand)
#max_y = max(data.Demand)
#main_ax.fill_between(zoom, min_y, max_y, facecolor='blue', alpha=0.5, zorder=0)
#main_ax.set_title(f'Demanda serie temporal: {data.index.min()}, {data.index.max()}', fontsize=10)
#main_ax.set_xlabel('')
#zoom_ax = fig.add_subplot(grid[5:, :])
#data.loc[zoom[0]: zoom[1]].Demand.plot(ax=zoom_ax, color='blue', linewidth=1)
#zoom_ax.set_title(f'Demanda : {zoom}', fontsize=10)
#zoom_ax.set_xlabel('')
#plt.subplots_adjust(hspace=1)
#plt.show();

"""ESTACIONALIDAD


"""

fig, axs = plt.subplots(2, 2, figsize=(8, 5), sharex=False, sharey=True)
axs = axs.ravel()

# Distribucion de demanda por mes
data['month'] = data.index.month
data.boxplot(column='Demand', by='month', ax=axs[0], flierprops={'markersize': 3, 'alpha': 0.3})
data.groupby('month')['Demand'].median().plot(style='o-', linewidth=0.8, ax=axs[0])
axs[0].set_ylabel('Demanda')
axs[0].set_title('Distribucion de demanda por mes', fontsize=9)

# Distribucion de demanda por dia de la semana
data['week_day'] = data.index.day_of_week + 1
data.boxplot(column='Demand', by='week_day', ax=axs[1], flierprops={'markersize': 3, 'alpha': 0.3})
data.groupby('week_day')['Demand'].median().plot(style='o-', linewidth=0.8, ax=axs[1])
axs[1].set_ylabel('Demanda')
axs[1].set_title('Distribucion de demanda por dia de la semana', fontsize=9)

# Distribución de la demanda por hora del día
data['hour_day'] = data.index.hour + 1
data.boxplot(column='Demand', by='hour_day', ax=axs[2], flierprops={'markersize': 3, 'alpha': 0.3})
data.groupby('hour_day')['Demand'].median().plot(style='o-', linewidth=0.8, ax=axs[2])
axs[2].set_ylabel('Demand')
axs[2].set_title('Distribución de la demanda por hora del día', fontsize=9)

# Distribución de la demanda por día de la semana y hora del día
mean_day_hour = data.groupby(["week_day", "hour_day"])["Demand"].mean()
mean_day_hour.plot(ax=axs[3])
axs[3].set(
    title       = "Demanda media durante la semana",
    xticks      = [i * 24 for i in range(7)],
    xticklabels = ["Lun", "Mar", "Mier", "Juev", "Vie", "Sab", "Dom"],
    xlabel      = "Día y hora",
    ylabel      = "Number of Demand"
)
axs[3].title.set_size(10)

fig.suptitle("Gráficos de estacionalidad", fontsize=12)
fig.tight_layout()

"""GRAFICA MEJORADA"""

import matplotlib.pyplot as plt

# 👉 Quitar fondo gris
plt.style.use('default')

# Configuración estilo MDPI-like
plt.rcParams.update({
    "font.size": 8,
    "font.family": "serif",
    "axes.titlesize": 9,
    "axes.labelsize": 8,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
})

fig, axs = plt.subplots(2, 2, figsize=(7, 5))
axs = axs.ravel()

# 👉 Fondo blanco
for ax in axs:
    ax.set_facecolor('white')

# --- MES ---
data['month'] = data.index.month
data.boxplot(column='Demand', by='month', ax=axs[0], grid=False,
             flierprops={'markersize': 2, 'alpha': 0.3})
axs[0].set_title('')

data.groupby('month')['Demand'].median().plot(
    style='o-', color='black', markersize=3, ax=axs[0]
)

axs[0].set_ylabel('Demanda [MW]')
axs[0].tick_params(direction='in')
axs[0].set_xlabel('(a) Distribucion Mensual')

# --- DÍA SEMANA ---
data['week_day'] = data.index.day_of_week + 1
data.boxplot(column='Demand', by='week_day', ax=axs[1], grid=False,
             flierprops={'markersize': 2, 'alpha': 0.3})
axs[1].set_title('')

data.groupby('week_day')['Demand'].median().plot(
    style='o-', color='black', markersize=3, ax=axs[1]
)

axs[1].set_ylabel('Demanda [MW]')
axs[1].tick_params(direction='in')
axs[1].set_xlabel('(b) Distribucion semanal')

# --- HORA ---
data['hour_day'] = data.index.hour + 1
data.boxplot(column='Demand', by='hour_day', ax=axs[2], grid=False,
             flierprops={'markersize': 2, 'alpha': 0.3})
axs[2].set_title('')

data.groupby('hour_day')['Demand'].median().plot(
    style='o-', color='black', markersize=3, ax=axs[2]
)

axs[2].set_ylabel('Demanda [MW]')
axs[2].tick_params(direction='in')
axs[2].set_xlabel('(c) Distribucion Horaria')

# --- DÍA + HORA ---
mean_day_hour = data.groupby(["week_day", "hour_day"])["Demand"].mean()
mean_day_hour.plot(color='black', ax=axs[3])

axs[3].set(
    xticks=[i * 24 for i in range(7)],
    xticklabels=["Lun", "Mar", "Mier", "Jue", "Vie", "Sab", "Dom"],
    xlabel='(d) Promedio horario semanal',
    ylabel="Demanda [MW]"
)
axs[3].tick_params(direction='in')

# ❌ quitar título automático
plt.suptitle("")

# 👉 TÍTULO GENERAL
#fig.suptitle("Gráficas de estacionalidad", fontsize=11)

# Ajuste fino
fig.tight_layout(rect=[0, 0.03, 1, 0.95])

#plt.savefig("figura.eps", bbox_inches='tight')

plt.show()

"""Gráfico de autocorrelación"""

# Gráfico de autocorrelación
# ==============================================================================
#fig, ax = plt.subplots(figsize=(5, 2))
#plot_acf(data['Demand'], ax=ax, lags=336)
#plt.show()

# Partial autocorrelation plot
# ==============================================================================
#fig, ax = plt.subplots(figsize=(5, 2))
#plot_pacf(data['Demand'], ax=ax, lags=336)
#plt.show()

# Top 10 lags with the highest absolute partial autocorrelation
# ==============================================================================
calculate_lag_autocorrelation(
    data    = data['Demand'],
    n_lags  = 48*7,
    sort_by = "partial_autocorrelation_abs"
).head(10)

"""**CREACION DEL PREDICTOR**


"""

# BASELINE 1 SEMANA ANTES
# ==============================================================================
forecaster = ForecasterEquivalentDate(
                 offset    = pd.DateOffset(days=7),
                 n_offsets = 4
             )

# Train forecaster
# ==============================================================================
forecaster.fit(y=data.loc[:end_validation, 'Demand'])
forecaster

# Backtesting
# ==============================================================================
cv = TimeSeriesFold(
        steps              = 48,
        initial_train_size = len(data.loc[:end_validation]),
        refit              = False
)
metric1, predictions1 = backtesting_forecaster(
                          forecaster = forecaster,
                          y          = data['Demand'],
                          cv         = cv,
                          metric     = 'mean_absolute_error'
                       )

#pip install skforecast

# Create forecaster
# ==============================================================================
window_features = RollingFeatures(stats=["mean", "mean", "mean", "mean"], window_sizes=[48, 168, 672, 1008])
forecaster = ForecasterRecursive(
                 estimator       = LGBMRegressor(random_state=15926, verbose=-1),
                 lags            = [1, 2, 3, 4, 5, 6, 48, 96, 168, 336, 672, 1008, 2016],
                 window_features = window_features
             )

# Train forecaster
# ==============================================================================
forecaster.fit(y=data.loc[:end_validation, 'Demand'])
forecaster

# Backtesting
# ==============================================================================
metric2, predictions2 = backtesting_forecaster(
                          forecaster    = forecaster,
                          y             = data['Demand'],
                          cv            = cv,
                          metric        = 'mean_absolute_error',
                          verbose       = True, # Set to False to avoid printing
                      )

fig = go.Figure()
trace1 = go.Scatter(x=data_test.index, y=data_test['Demand'], name="test", mode="lines")
trace2 = go.Scatter(x=predictions1.index, y=predictions1['pred'], name="prediction", mode="lines")
trace3 = go.Scatter(x=predictions2.index, y=predictions2['pred'], name="prediction2", mode="lines")
fig.add_trace(trace1)
fig.add_trace(trace2)
fig.add_trace(trace3)
fig.update_layout(
    title="Real value vs predicted in test data",
    xaxis_title="Date time",
    yaxis_title="Demand",
    width=800,
    height=400,
    margin=dict(l=20, r=20, t=35, b=20),
    legend=dict(orientation="h", yanchor="top", y=1.01, xanchor="left", x=0)
)
fig.show()
fig.write_html('prediction_vs_real_test.html')
from IPython.display import HTML
HTML(filename='prediction_vs_real_test.html')

"""# VARIABLES EXOGENAS"""

# Dias del calendario
features_to_extract = [
    'month',
    'week',
    'day_of_week',
    'hour'
]
calendar_transformer = DatetimeFeatures(
    variables           = 'index',
    features_to_extract = features_to_extract,
    drop_original       = True,
)
calendar_features = calendar_transformer.fit_transform(data)[features_to_extract]
calendar_features

# posicion del sol
# ==============================================================================
location = LocationInfo(
    latitude  = -12.04318,
    longitude = -77.02824,
    timezone  = 'America/Lima'
)
sunrise_hour = [
    sun(location.observer, date=date, tzinfo=location.timezone)['sunrise']
    for date in data.index
]
sunset_hour = [
    sun(location.observer, date=date, tzinfo=location.timezone)['sunset']
    for date in data.index
]
sunrise_hour = pd.Series(sunrise_hour, index=data.index).dt.round("h").dt.hour
sunset_hour = pd.Series(sunset_hour, index=data.index).dt.round("h").dt.hour
sun_light_features = pd.DataFrame({
                        'sunrise_hour': sunrise_hour,
                        'sunset_hour': sunset_hour
                     })
sun_light_features['daylight_hours'] = (
    sun_light_features['sunset_hour'] - sun_light_features['sunrise_hour']
)
sun_light_features["is_daylight"] = np.where(
    (data.index.hour >= sun_light_features["sunrise_hour"])
    & (data.index.hour < sun_light_features["sunset_hour"]),
    1,
    0,
)

# IMPORTAR DESDE DRIVE
import pandas as pd
data_inicial = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/SCRIPTS/ARTICULO/PARA LA OPERACION/CON TODAS LAS VARIABLES EXOGENAS/DATA_COES-TEMP-HOLL-PIB-ACC-POBL.csv')
data_inicial.info()
data_inicial

# DIAS FESTIVOS
# ==============================================================================
holiday_features = data_inicial[['Holliday']].astype(int)
holiday_features['holiday_previous_day'] = holiday_features['Holliday'].shift(48)
holiday_features['holiday_next_day'] = holiday_features['Holliday'].shift(-48)
holiday_features.info()

# IMPORTAR DESDE DRIVE
import pandas as pd
data_1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/SCRIPTS/ARTICULO/PARA LA OPERACION/CON TODAS LAS VARIABLES EXOGENAS/DATA_COES-TEMP-HOLL-PIB-ACC-POBL.csv')
data.info()
data

PIB_features = data_1[['PIB']].astype(int)
PIB_features['PIB_previous_day'] = PIB_features['PIB'].shift(48)
PIB_features['PIB_next_day'] = PIB_features['PIB'].shift(-48)
PIB_features.info()

sin_acceso_features = data_1[['sin_acceso']].astype(int)
sin_acceso_features['sin_acceso_previous_day'] = sin_acceso_features['sin_acceso'].shift(48)
sin_acceso_features['sin_acceso_next_day'] = sin_acceso_features['sin_acceso'].shift(-48)
sin_acceso_features.info()

poblacion_features = data_1[['poblacion']].astype(int)
poblacion_features['poblacion_previous_day'] = poblacion_features['poblacion'].shift(48)
poblacion_features['poblacion_next_day'] = poblacion_features['poblacion'].shift(-48)
poblacion_features.info()

# Rolling windows of temperature
# ==============================================================================

# First, ensure data_inicial has a proper DatetimeIndex and frequency
data_exog_temp = data_inicial.copy()
data_exog_temp['Time'] = pd.to_datetime(data_exog_temp['Time'])
data_exog_temp = data_exog_temp.set_index('Time')
data_exog_temp = data_exog_temp.asfreq(data.index.freq) # Align frequency with `data`
data_exog_temp = data_exog_temp.sort_index()

# Extract Temperature, ensuring it aligns with the `data` DataFrame's index
# Reindex ensures that the temperature data matches the time index of the `data` DataFrame
temperature_series = data_exog_temp['Temperature'].reindex(data.index)

wf_transformer = WindowFeatures(
    variables   = ['Temperature'],
    window       = ["1D", "7D"],
    functions   = ["mean", "max", "min"],
    freq        = "30min", # Corrected frequency to match data
)
temp_features = wf_transformer.fit_transform(temperature_series.to_frame())
temp_features.info()

# Merge all exogenous variables
# ==============================================================================

# Re-process holiday_features to align its index with data.index
# This is necessary because data_inicial had a default integer index and a different
# number of rows compared to the `data` DataFrame used to create other features.
holiday_features_processed = data_inicial.copy()
holiday_features_processed['Time'] = pd.to_datetime(holiday_features_processed['Time'])
holiday_features_processed = holiday_features_processed.set_index('Time')
holiday_features_processed = holiday_features_processed.asfreq(data.index.freq)
holiday_features_processed = holiday_features_processed.sort_index()
holiday_features = holiday_features_processed[['Holliday']].reindex(data.index)

# PIB ADAPTACION A LA DTA EXOG
PIB_features_processed = data_inicial.copy()
PIB_features_processed['Time'] = pd.to_datetime(PIB_features_processed['Time'])
PIB_features_processed = PIB_features_processed.set_index('Time')
PIB_features_processed = PIB_features_processed.asfreq(data.index.freq)
PIB_features_processed = PIB_features_processed.sort_index()
PIB_features = PIB_features_processed[['PIB']].reindex(data.index)

# brecha de acceso a la electricidad ADAPTACION A LA DTA EXOG
sin_acceso_features_processed = data_inicial.copy()
sin_acceso_features_processed['Time'] = pd.to_datetime(sin_acceso_features_processed['Time'])
sin_acceso_features_processed = sin_acceso_features_processed.set_index('Time')
sin_acceso_features_processed = sin_acceso_features_processed.asfreq(data.index.freq)
sin_acceso_features_processed = sin_acceso_features_processed.sort_index()
sin_acceso_features = sin_acceso_features_processed[['sin_acceso']].reindex(data.index)


# poblacion ADAPTACION A LA DTA EXOG
poblacion_features_processed = data_inicial.copy()
poblacion_features_processed['Time'] = pd.to_datetime(poblacion_features_processed['Time'])
poblacion_features_processed = poblacion_features_processed.set_index('Time')
poblacion_features_processed = poblacion_features_processed.asfreq(data.index.freq)
poblacion_features_processed = poblacion_features_processed.sort_index()
poblacion_features = poblacion_features_processed[['poblacion']].reindex(data.index)


assert all(calendar_features.index == sun_light_features.index)
assert all(calendar_features.index == temp_features.index)
assert all(calendar_features.index == holiday_features.index)
assert all(calendar_features.index == PIB_features.index)
assert all(calendar_features.index == sin_acceso_features.index)
assert all(calendar_features.index == poblacion_features.index)

exogenous_features = pd.concat([
                         calendar_features,
                         sun_light_features,
                         temp_features,
                         holiday_features,
                         PIB_features,
                         sin_acceso_features,
                         poblacion_features
                     ], axis=1)

# Due to the creation of moving averages, there are missing values at the beginning
# of the series. And due to holiday_next_day there are missing values at the end.
exogenous_features = exogenous_features.iloc[7 * 48:, :]
exogenous_features = exogenous_features.iloc[:-48, :]
exogenous_features

# Cliclical encoding of calendar and sunlight features
# ==============================================================================
features_to_encode = [
    "month",
    "week",
    "day_of_week",
    "hour",
    "sunrise_hour",
    "sunset_hour",
]
max_values = {
    "month": 12,
    "week": 52,
    "day_of_week": 6,
    "hour": 24,
    "sunrise_hour": 6,
    "sunset_hour": 18,
}
cyclical_encoder = CyclicalFeatures(
    variables     = features_to_encode,
    max_values    = max_values,
    drop_original = False
)

exogenous_features = cyclical_encoder.fit_transform(exogenous_features)
exogenous_features.head(3)

# Interaction between exogenous variables
# ==============================================================================
transformer_poly = PolynomialFeatures(
                        degree           = 2,
                        interaction_only = True,
                        include_bias     = False
                    ).set_output(transform="pandas")
poly_cols = [
    'month_sin',
    'month_cos',
    'week_sin',
    'week_cos',
    'day_of_week_sin',
    'day_of_week_cos',
    'hour_sin',
    'hour_cos',
    'sunrise_hour_sin',
    'sunrise_hour_cos',
    'sunset_hour_sin',
    'sunset_hour_cos',
    'daylight_hours',
    'is_daylight',
    # 'holiday_previous_day', # These columns are not present in exogenous_features
    # 'holiday_next_day',     # These columns are not present in exogenous_features
    'Temperature_window_1D_mean',
    'Temperature_window_1D_min',
    'Temperature_window_1D_max',
    'Temperature_window_7D_mean',
    'Temperature_window_7D_min',
    'Temperature_window_7D_max',
    'Temperature',
    'Holliday',
    'PIB',
    'sin_acceso',
    'poblacion'
]
poly_features = transformer_poly.fit_transform(exogenous_features[poly_cols])
poly_features = poly_features.drop(columns=poly_cols)
poly_features.columns = [f"poly_{col}" for col in poly_features.columns]
poly_features.columns = poly_features.columns.str.replace(" ", "__")
assert all(poly_features.index == exogenous_features.index)
exogenous_features = pd.concat([exogenous_features, poly_features], axis=1)
exogenous_features

# Select exogenous variables to be included in the model
# ==============================================================================
exog_features = []
# Columns that ends with _sin or _cos are selected
exog_features.extend(exogenous_features.filter(regex='_sin$|_cos$').columns.tolist())
# Columns that start with Temperature_ are selected
exog_features.extend(exogenous_features.filter(regex='^Temperature_.*').columns.tolist())
# Columns that start with Holiday_ are selected
exog_features.extend(exogenous_features.filter(regex='^Holiday_.*').columns.tolist())
# Include original features
exog_features.extend(['Temperature', 'Holliday','PIB','sin_acceso','poblacion'])

# ENSURE UNIQUE NAMES TO AVOID PANDAS/SKFORECAST ERRORS
exog_features = list(dict.fromkeys(exog_features))
exog_features

# Merge target and exogenous variables in the same DataFrame
# ==============================================================================
data = data[['Demand']].merge(
           exogenous_features[exog_features],
           left_index  = True,
           right_index = True,
           how         = 'inner'  # Use only dates for which we have all the variables
       )
data = data.astype('float32')

data
#data.to_csv("datos_demanda.csv", index=True)

# Split data into train-val-test
data_train = data.loc[: end_train, :].copy()
data_val   = data.loc[end_train:end_validation, :].copy()
data_test  = data.loc[end_validation:, :].copy()

"""**ENTRENAMIENTO Y VALIDACION**"""

exog       = data[exog_features]
exog

# Backtesting model
# ==============================================================================
metric3, predictions3 = backtesting_forecaster(
                          forecaster = forecaster,
                          y          = data['Demand'],
                          exog       = data[exog_features],
                          cv         = cv,
                          metric     = 'mean_absolute_error'
                      )
display(metric3)
predictions3.head()
forecaster

exog = data[exog_features]
print(exog.info())
display(exog.head())

display(metric3)
predictions3.head()

fig = go.Figure()
trace1 = go.Scatter(x=data_test.index, y=data_test['Demand'], name="REAL", mode="lines",line=dict(color='black'))
trace2 = go.Scatter(x=predictions1.index, y=predictions1['pred'], name="CON DATA REGRESSOR", mode="lines")
trace3 = go.Scatter(x=predictions2.index, y=predictions2['pred'], name="prediction LGBM", mode="lines")
trace4 = go.Scatter(x=predictions3.index, y=predictions3['pred'], name="prediction_exog_PIB", mode="lines")
fig.add_trace(trace1)
fig.add_trace(trace2)
fig.add_trace(trace3)
fig.add_trace(trace4)
fig.update_layout(
    title="Demanda Real vs Prediccion de demanda",
    xaxis_title="Fecha (h/m/año)",
    yaxis_title="Demanda (MW)",
    width=800,
    height=400,
    margin=dict(l=20, r=20, t=35, b=20),
    legend=dict(orientation="h", yanchor="top", y=1.01, xanchor="left", x=0)
)
fig.show()
fig.write_html('prediction_vs_real_test.html')
from IPython.display import HTML
HTML(filename='prediction_vs_real_test.html')

display(metric1)
display(metric2)
display(metric3)

"""**HIPERPARAMETROS**"""

# ==============================================================================
forecaster = ForecasterRecursive(
                 regressor       = LGBMRegressor(random_state=15926, verbose=-1),
                 lags            = 48*7,
                 window_features = window_features
                 #weight_func = custom_weights
             )


lags_grid = [48, (1, 2, 3, 30, 49, 97, 48, 145, 289, 193)]


def search_space(trial):
    search_space  = {
        'n_estimators' : trial.suggest_int('n_estimators', 100, 900, step=100),
        'max_depth'    : trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.5),
        'reg_alpha'    : trial.suggest_float('reg_alpha', 0, 1),
        'reg_lambda'   : trial.suggest_float('reg_lambda', 0, 1),
        'lags'         : trial.suggest_categorical('lags', lags_grid)
    }
    return search_space


cv_search = TimeSeriesFold(
                steps              = 48,
                initial_train_size = len(data[:end_train]),
                refit              = False,
            )

results_search, frozen_trial = bayesian_search_forecaster(
                                   forecaster   = forecaster,
                                   y            = data.loc[:end_validation, 'Demand'],
                                   exog         = data.loc[:end_validation, exog_features],
                                   cv           = cv_search,
                                   metric       = 'mean_absolute_error',
                                   search_space = search_space,
                                   n_trials     = 10,
                                   return_best  = True
                               )

best_params = results_search.at[0, 'params']
best_params = best_params | {'random_state': 15926, 'verbose': -1}
best_lags = results_search.at[0, 'lags']
results_search.head(3)

metric4, predictions4 = backtesting_forecaster(
                          forecaster = forecaster,
                          y          = data['Demand'],
                          exog       = data[exog_features],
                          cv         = cv,
                          metric     ='mean_absolute_error'

                      )
display(metric4)
predictions4.head()

fig = go.Figure()
trace1 = go.Scatter(x=data_test.index, y=data_test['Demand'], name="REAL", mode="lines",line=dict(color='black'))
trace2 = go.Scatter(x=predictions1.index, y=predictions1['pred'], name="BASELINE", mode="lines")
trace3 = go.Scatter(x=predictions2.index, y=predictions2['pred'], name="LGBMR", mode="lines")
trace4 = go.Scatter(x=predictions3.index, y=predictions3['pred'], name="LGBMR_exog_socioec", mode="lines")
trace5 = go.Scatter(x=predictions4.index, y=predictions4['pred'], name="LGBMR_exog_socioec+Optm", mode="lines")
fig.add_trace(trace1)
fig.add_trace(trace2)
fig.add_trace(trace3)
fig.add_trace(trace4)
fig.add_trace(trace5)
fig.update_layout(
    title={
        'text': "<b>Demanda Real vs Predicción de demanda</b>",
        'y':0.95,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': {
            'family': 'Arial, sans-serif',
            'size': 18,
            'color': 'black'
        }
    },
    xaxis_title={
        'text': "<b>Fecha (h/m/año)</b>",
        'font': {
            'family': 'Arial, sans-serif',
            'size': 14,
            'color': 'black'
        }
    },
    yaxis_title={
        'text': "<b>Demanda (MW)</b>",
        'font': {
            'family': 'Arial, sans-serif',
            'size': 14,
            'color': 'black'
        }
    },
    width=800,
    height=400,
    margin=dict(l=20, r=20, t=35, b=20),
    legend=dict(orientation="h", yanchor="bottom", y=-0.4, xanchor="center", x=0.5),
    paper_bgcolor='white',
    plot_bgcolor='white',
    xaxis=dict(showgrid=True, showline=True, linewidth=1, linecolor='black'),
    yaxis=dict(showgrid=True, showline=True, linewidth=1, linecolor='black')
)
fig.show()
fig.write_html('prediction_vs_real_test.html')
from IPython.display import HTML
HTML(filename='prediction_vs_real_test.html')


from skforecast.metrics import symmetric_mean_absolute_percentage_error
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

y_true = data_test['Demand']


y_pred1 = predictions1['pred']
y_true_aligned1, y_pred1_aligned = y_true.align(y_pred1, join='inner', fill_value=np.nan)
rmse1 = np.sqrt(mean_squared_error(y_true_aligned1, y_pred1_aligned))
smape1 = symmetric_mean_absolute_percentage_error(y_true_aligned1, y_pred1_aligned)
r2_1 = r2_score(y_true_aligned1, y_pred1_aligned)
MAE1 = metric1.iloc[0,0]


y_pred2 = predictions2['pred']
y_true_aligned2, y_pred2_aligned = y_true.align(y_pred2, join='inner', fill_value=np.nan)
rmse2 = np.sqrt(mean_squared_error(y_true_aligned2, y_pred2_aligned))
smape2 = symmetric_mean_absolute_percentage_error(y_true_aligned2, y_pred2_aligned)
r2_2 = r2_score(y_true_aligned2, y_pred2_aligned)
MAE2 = metric2.iloc[0,0]


y_pred3 = predictions3['pred']
y_true_aligned3, y_pred3_aligned = y_true.align(y_pred3, join='inner', fill_value=np.nan)
rmse3 = np.sqrt(mean_squared_error(y_true_aligned3, y_pred3_aligned))
smape3 = symmetric_mean_absolute_percentage_error(y_true_aligned3, y_pred3_aligned)
r2_3 = r2_score(y_true_aligned3, y_pred3_aligned)
MAE3 = metric3.iloc[0,0]


y_pred4 = predictions4['pred']
y_true_aligned4, y_pred4_aligned = y_true.align(y_pred4, join='inner', fill_value=np.nan)
rmse4 = np.sqrt(mean_squared_error(y_true_aligned4, y_pred4_aligned))
smape4 = symmetric_mean_absolute_percentage_error(y_true_aligned4, y_pred4_aligned)
r2_4 = r2_score(y_true_aligned4, y_pred4_aligned)
MAE4 = metric4.iloc[0,0]

print("\n--- Baseline Model (predictions1) ---")
print(f"RMSE: {rmse1:.2f}")
print(f"SMAPE: {smape1:.2f}%")
print(f"R-squared: {r2_1:.2f}")
print(f"MAE: {MAE1:.2f}")

print("\n--- LGBMRegressor Model (predictions2) ---")
print(f"RMSE: {rmse2:.2f}")
print(f"SMAPE: {smape2:.2f}%")
print(f"R-squared: {r2_2:.2f}")
print(f"MAE: {MAE2:.2f}")

print("\n--- LGBMRegressor with Exogenous Model (predictions3) ---")
print(f"RMSE: {rmse3:.2f}")
print(f"SMAPE: {smape3:.2f}%")
print(f"R-squared: {r2_3:.2f}")
print(f"MAE: {MAE3:.2f}")

print("\n--- Optimized LGBMRegressor with Exogenous Model (predictions4) ---")
print(f"RMSE: {rmse4:.2f}")
print(f"SMAPE: {smape4:.2f}%")
print(f"R-squared: {r2_4:.2f}")
print(f"MAE: {MAE4:.2f}")

import pandas as pd

tabla_mdpi = pd.DataFrame({
    'Modelo': [
        'Caso 1: Baseline',
        'Caso 2: LGBM',
        'Caso 3: LGBM + Exógenas',
        'Caso 4: LGBM + Exógenas + Optimización'
    ],
    'RMSE': [rmse1, rmse2, rmse3, rmse4],
    'SMAPE (%)': [smape1, smape2, smape3, smape4],
    'R²': [r2_1, r2_2, r2_3, r2_4],
    'MAE': [MAE1, MAE2, MAE3, MAE4]
})


tabla_mdpi = tabla_mdpi.round(2)
display(tabla_mdpi.style.hide(axis="index"))
tabla_mdpi = tabla_mdpi.rename(columns={'Modelo': 'Caso'})

tabla_mdpi = tabla_mdpi.round(2)

